### ISSUE TITLE
Multi-Core Execution not proceeding

### ISSUE THREAD

**Issue by Upasna55** [yousei-github/ChampSim-Ramulator#5]
Hello Yousei

I want to execute 8 core runs, so I've passed the trace argument 8 times, as follows:
`$EXECUTION --warmup-instructions $N_WARM --simulation-instructions $N_SIM --stats $FILENAME $CFG1 $CFG2 $TRACE2 $TRACE2 $TRACE2 $TRACE2 $TRACE2 $TRACE2 $TRACE2 $TRACE2` 

In addition, I've assigned `NUM_CPUS = 8` value in `include/ChampSim/champsim_constants.h`. After re-compilation,  when I execute the above command, the simulation gets stuck as follows:
![Screenshot from 2024-03-02 21-27-06](https://github.com/yousei-github/ChampSim-Ramulator/assets/91068864/a038987e-6656-4f04-856c-803e84d3f5e1)

However, For `NUM_CPUS=2` and two trace arguments in the execution command, the simulation works fine. Can you please guide me to execute multi-core runs, when number of cores are more than 2.

Thanks &  Regards
Upasna

**Comment by yousei-github** [comment]
Hello, I will check it on the weekend

**Comment by yousei-github** [comment]
Oh, if you want to execute multi-core simulation like 8 core, you might need to add some source code...

For example, when searching the preprocessor `#if (CPU_USE_MULTIPLE_CORES == ENABLE)`, you will find the source code for executing a 2-core simulation. So, to upgrade it to the 8-core version, you need to add source code, such as:

```
    champsim::channel cpuXxx_STLB_to_cpuXxx_PTW_queues {32, 0, 0, LOG2_PAGE_SIZE, 0};
    champsim::channel cpuXxx_DTLB_to_cpuXxx_STLB_queues {32, 32, 32, LOG2_PAGE_SIZE, 0};
    champsim::channel cpuXxx_ITLB_to_cpuXxx_STLB_queues {32, 32, 32, LOG2_PAGE_SIZE, 0};
    champsim::channel cpuXxx_L2C_to_cpuXxx_STLB_queues {32, 32, 32, LOG2_PAGE_SIZE, 0};
    champsim::channel cpuXxx_L1D_to_cpuXxx_L2C_queues {32, 32, 32, LOG2_BLOCK_SIZE, 0};
    champsim::channel cpuXxx_L1I_to_cpuXxx_L2C_queues {32, 32, 32, LOG2_BLOCK_SIZE, 0};
    champsim::channel cpuXxx_to_cpuXxx_L1I_queues {32, 32, 32, LOG2_BLOCK_SIZE, 1};
    champsim::channel cpuXxx_PTW_to_cpuXxx_L1D_queues {32, 32, 32, LOG2_BLOCK_SIZE, 1};
    champsim::channel cpuXxx_to_cpuXxx_L1D_queues {32, 32, 32, LOG2_BLOCK_SIZE, 1};
    champsim::channel cpuXxx_L1I_to_cpuXxx_ITLB_queues {16, 16, 16, LOG2_PAGE_SIZE, 1};
    champsim::channel cpuXxx_L1D_to_cpuXxx_DTLB_queues {16, 16, 16, LOG2_PAGE_SIZE, 1};
    champsim::channel cpuXxx_L2C_to_LLC_queues {32, 32, 32, LOG2_BLOCK_SIZE, 0};
```
where Xxx is from 2 to 7.

(It might take some time (/ω＼))

**Comment by Upasna55** [comment]
Yousei, I already added the code in `main.h` but even after that it's not working. PFA the file with requisite modifications.
[main_h.txt](https://github.com/yousei-github/ChampSim-Ramulator/files/14627571/main_h.txt)

Further, I've also made the necessary modifications in `champsim_constants.h` for extending to multiple cores.

PS: File attached in .txt format as .h is not supported to upload here.

Thanks & Regards
Upasna

**Comment by Upasna55** [comment]
Hello Yousei

Could you get time to check the modified `main.h` file attached in my previous comment? For more than 4 cores, ChampSim-Ramulator setup is still not working.

Best Regards
Upasna

**Comment by yousei-github** [comment]
Hello Upasna55

I just found that the specified CPU IDs for each PTW are not correct. Fix is here, 502d2191241f007af3e8a58235cb941e442a1922.
I will try to test the multiple-core simulation. Maybe this fix could solve your problem.

**Comment by Upasna55** [comment]
Hello Yousei

I tried this fix, but somehow it still didn't work out. 

Regards
Upasna

**Comment by yousei-github** [comment]
What happen if you disable the PRINT_STATISTICS_INTO_FILE like,
`#define PRINT_STATISTICS_INTO_FILE           (DISABLE)`

**Comment by Upasna55** [comment]
Yousei, disabling printing stats into file works! but we need statistics file as well. How's this file writing operation halting the 8-core simulation?

Thanks & Regards
Upasna

**Comment by yousei-github** [comment]
Yeah, I'm also wondering why it happens...

I'll try to debug the source code when I have time.

**Comment by yousei-github** [comment]
Find out the reason is that the length of statistics file is too long to open. Now, if the file name is too long, a short name will be used instead, like `file_open_retry_Xxx`

Commit: ef883c0444ea84e7b0c8f715c1e097550f4987e5

**Comment by Upasna55** [comment]
Thank you Yousei. It's working now!

Best Regards
Upasna
